//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pricebook.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pricebook.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENDORID,COMPANYNM
        ///100,AMAZON
        ///2000,ADVANCED RETAIL PRODUCTS
        ///2100,ALBINA FUEL
        ///2140,AURORA PLASTICS &amp; PACKAGING
        ///2145,BARGREEN ELLINGSON
        ///2157,BLUE RIBBON OFFICE SUPPLY
        ///2300,BONITA PIONEER PACKAGING
        ///2400,&quot;BOTS COMPANY, INC.&quot;
        ///2500,&quot;BRANCH DISTRIBUTING, INC.&quot;
        ///2530,BRP BOX SHOP
        ///2556,OFFICE DEPOT
        ///4540,ALSCO-AMERICAN LINEN DIVISION
        ///4799,A-1 COUPLING &amp; HOSE
        ///4803,ALLIANCE PACKAGING
        ///4804,ALLIANCE PLASTICS
        ///4805,ALLIED FASTENING SUPPLY
        ///4806,&quot;AMERICAN NETTING &amp; FABRIC, INC.&quot;
        ///4807,ALLSTATE PLASTICS
        ///4808, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string APVENDOR_Small {
            get {
                return ResourceManager.GetString("APVENDOR_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTNO,COMPANYNM,ADDRESS1,CITY,STATE,Zip,PERSON,PHONE,FAX,EMAIL
        ///50001,CASH SALES,ss,PORTLAND,OR,97214,NULL,(503)235-8341,NULL,NULL
        ///50140,11TH AVE LIQUOR,1040 SE HAWTHORNE,PORTLAND,OR,97214,NULL,(503)236-2076,(503)236-2520,NULL
        ///50200,39TH ST. MINI MART -WA,210 E 39TH STREET,VANCOUVER,WA,98663,NULL,(360)693-8411,NULL,NULL
        ///50201,82ND GAS FOR LESS,5322 SE 82ND AVE.,PORTLAND,OR,97266,,(503)772-5353,,
        ///50363,A1 SMOKESHOP,1590 SHERMAN AVENUE,NORTH BEND,OR,97459,,(541)808-0586,,
        ///50500,ADVANCED MACHINING,117 N  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ARCUST {
            get {
                return ResourceManager.GetString("ARCUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP,CATG,DESCRIP
        ///B,B,B
        ///B-01,B,*SIPP ECO BEVERAGE CO.*
        ///F,F,F
        ///F-01,F,*GROCERY &amp; CARRY BAGS*
        ///F-01A,F,*LIQUOR STORE GROCERY BAG
        ///F-01AA,F,   
        ///F-01B,F,*T-SHIRT BAG*
        ///F-01C,F,*HANDLE &amp; SHOPPING BAGS*
        ///F-01D,F,*WHITE BAGS*
        ///F-01E,F,*SUPER WAVE CARRY BAGS*
        ///F-02,F,*PAPER BREAD BAGS*
        ///F-03,F,*MERCHANDISE BAGS*
        ///F-03C,F,*COFFEE BAGS*
        ///F-04,L,*PLASTIC BAGS*
        ///F-04A,F,&quot;PRODUCE BAGS*
        ///F-04C	F	*APPLE HANDLE PRODUCE BAGS*
        ///F-05	F	*PADDED BAGS*
        ///F-06	F	*SANITARY NAPKIN BAGS*
        ///F-07	F	*SANDWICH/GREASE PROOF BAGS*
        ///F-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INVGROUP_Small {
            get {
                return ResourceManager.GetString("INVGROUP_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITEMNO,CATG,GROUP,SUPERGROUP,DESCRIP,DESCRIP2,DESCRIP3,W_AVG_COST,LINECOST,DEADNET,LOADEDCOST,ONORDER,ORDERQTY,VENDORID,VENDORITEM,DELIV_DAYS,DAYS_OH,FLAG_PDAYS,LASTDATE,BACKORDTF,WHSE_LOC,WHSE_BIN,RTDESC1,RTDESC2,SELLROUND,SELLUOM,BUY_UOM,ITEMSTATUS,PRBK_SEQ,SELL_CALC1,SELL_CALC2,SELL_CALC3,SELL_CALC4,SELL_CALC5,SELL_CALC6,SELL_CALC7,SELL_CALC8,SELL_CALC9
        ///4,G,G-99,DRUM CHARG,IMPRINT CHARGE FOR TUMBLER,1 COLOR,NULL,0,0,0,0,0,1,5675,NULL,0,0,30,NULL,0,,,1/EACH,EACH,5,EACH,EACH,A,9999,NULL,NULL,NULL,NULL,NUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INVMAS {
            get {
                return ResourceManager.GetString("INVMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITEMNO,SHIPCUSTNO,LastSellNetnet,EntryDate,CATG,GROUP,DESCRIP,DESCRIP2,DESCRIP3
        ///5,73725,27.6,12/10/2014 0:00,G,G-99,ARTWORK &amp; PLATE CHARGES,NULL,NULL
        ///5,53375,390,4/29/2015 6:18,G,G-99,ARTWORK &amp; PLATE CHARGES,NULL,NULL
        ///5,73203,700,10/27/2015 9:53,G,G-99,ARTWORK &amp; PLATE CHARGES,NULL,NULL
        ///5,57900,800,8/18/2015 8:51,G,G-99,ARTWORK &amp; PLATE CHARGES,NULL,NULL
        ///5,67055,170,9/14/2015 13:05,G,G-99,ARTWORK &amp; PLATE CHARGES,NULL,NULL
        ///5,52585,210,2/26/2016 9:46,G,G-99,ARTWORK &amp; PLATE CHARGES,NULL,NULL
        ///5,54445,75,4/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ORDERFRM_Plus {
            get {
                return ResourceManager.GetString("ORDERFRM_Plus", resourceCulture);
            }
        }
    }
}
